# Generated by Django 5.0.1 on 2026-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default='Popular', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Stored as JSON string or plain text'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions',
            field=models.TextField(blank=True, help_text='Stored as JSON string or plain text'),
        ),
    ]
