# Generated by Django 5.0.1 on 2026-03-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videoview',
            name='unique_view',
        ),
        migrations.AddField(
            model_name='videoview',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='videoview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'video'), name='unique_user_video_view'),
        ),
    ]
