# Generated by Django 5.0.1 on 2026-03-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_videoview_unique_view_videoview_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default='Veg', max_length=100),
        ),
    ]
