# Generated by Django 5.0.1 on 2026-04-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, default='00:00', max_length=10),
        ),
    ]
